server:
  port: 16005

# ?????
spring:
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/springSecurityDb?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: root
      password: liu2020
