server:
  port: 16006
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springsecuritydb?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: liu2020