server:
  port: 8061

#mybatis-plus映射mapper文件
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.bytespaces.system.entity

#设置为true，表示后发现的bean会覆盖之前相同名称的bean。
shardingsphere:
  fresh: {"dataone":"dataone"}
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: sharing-sphere-server
  mvc:
    servlet:
      path: /sharding
  shardingsphere:
    datasource:
      names: ds01,ds02
      ds01:
        driver-class-name: com.mysql.cj.jdbc.Driver
        test-whileidle: true
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3306/master_one?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
        username: root
        password: liu2020
        validation-query: select 1 from dual
      ds02:
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3306/salve_one?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
        username: root
        password: liu2020
        validation-query: select 1 from dual
    props:
      sql:
        show: true
    sharding:
      default-data-source-name: ds01
      tables:
        dataone:
          actual-data-nodes: ds01.dataone
          table-strategy:
            standard:
              sharding-column: create_date
              precise-algorithm-class-name: com.bytespaces.config.sharedingsphere.DateOperationDayPreciseShardingAlgorithm
              range-algorithm-class-name: com.bytespaces.config.sharedingsphere.DateOperationDayRangeShardingAlgorithm
